### ISSUE TITLE
Cannot finish Aln1 (AlienBase)

### ISSUE THREAD

**Issue by ThibaultLemaire** [stuntrally/stuntrally#124] opened 2023-02-14 21:15 UTC
The very last checkpoint does not trigger. I noticed this in Championship, but can reproduce in Single Race mode. It is 100% reproducible on my machine.

I'm on NixOS (Linux) with a version 2.7 that I built myself.

**Comment by Calinou** [comment] 2023-02-14 23:53
I can reproduce this on the 2.7.1 Flatpak on Fedora 37.

**Comment by cryham** [comment] 2023-02-15 14:49
Right. I have this too. Any idea since when, only in 2.7?

**Comment by ThibaultLemaire** [comment] 2023-02-15 17:42
FTR, I've tried with the Jaguar and Fox.

I have a ghost on this track (and a very crisp memory of finishing it) from the current nixpkgs version (2.6.2).
The track seems to have been updated with sparkling effects between those two versions.

**Comment by Calinou** [comment] 2023-02-15 18:11
> Right. I have this too. Any idea since when, only in 2.7?

I remember being able to finish Aln1 in 2.6.

**Comment by ThibaultLemaire** [comment] 2023-02-24 22:10
Note however that it's playable in Reverse.

Although... Not before glitching out of a weird bug that I somehow cannot reproduce...

The first time I tried to play it in Reverse, it spawned me below one of the pipes (seemingly right below one of the checkpoints). I tried reloading the track a few times; Tried a few other tracks, but that only seemed to get worse as I sometimes wasn't spawning on a checkpoint. It was always the same spot for a given track though.

I reloaded the game and I could swear the issue was still there, so I was about to fill out a new issue here, but just for peace of mind, and to describe the reproducibility of it, decided to try out another car (I was playing with the Jaguar) in single race mode. I took one of the most basic tracks, TestC2, with the Fox, and ... Nothing wrong. Everything was working. I could switch back and forth between Reverse and forward modes, load different tracks, different cars...

I don't know what happened, but at least I can report that track is playable in reverse now

**Comment by ThibaultLemaire** [comment] 2023-02-24 22:27
Yep, that was the key. You *can* finish it in forward mode, you just have to find the finish line haha

It's around where I spawned in Reverse... And now I can apparently partly reproduce it. You can see the broken spawn location (and finish line) by toggling the Reverse checkbox in Single Race mode:

![image](https://user-images.githubusercontent.com/21345269/221304188-2ae74240-ac94-4840-a9fa-e78e9100e0ec.png)

**Comment by cryham** [comment] 2023-02-24 22:35
Fixed in tracks repo.
You can just replace road.xml to [this latest](https://raw.githubusercontent.com/stuntrally/tracks/master/Aln1-AlienBase/road.xml) to get it back to normal.
Yeah I made it not looped by accident, which meant finish is in own place, the default you found out.

**Closed** 2023-02-24 22:37 UTC

**Comment by ThibaultLemaire** [comment] 2023-02-25 10:42
Oh, awesome, thanks! And sorry, haha, I didn't know you fixed it like 3h before I posted... Talk about coincidence
