### ISSUE TITLE
Stunt Rally randomly crashes during map loading

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#84] opened 2022-09-13 11:36 UTC
Stunt Rally often crashes when loading maps with latest Stunt Rally from Git (5ce6dde7273e61bf504e4b60bd288bfeac3a8ecb + https://github.com/stuntrally/tracks/commit/bef80ff5cdec845c3d04b7066c7d96eb025332db) + latest OGRE (13.4.4) and default graphic presets (the only changes are fullscreen turned on + resolution changed to my native one). It now happens randomly, not every time. Sadly, I was not able to get any useful logs.

I am using AMD RX 6600 XT with Mesa 22.1.7.

If you are able to test it yourself on Linux with Flatpak support, here is my test build: https://github.com/flathub/org.tuxfamily.StuntRally/pull/7#issuecomment-1244790453

**Comment by AsciiWolf** [comment] 2022-09-13 11:38
Also, there is still a lot of stuttering as mentioned [here](https://github.com/stuntrally/stuntrally/issues/31#issuecomment-1245268345). It may be related.

**Comment by AsciiWolf** [comment] 2022-09-13 11:56
Ah, this may be https://github.com/stuntrally/stuntrally/issues/67#issuecomment-1207334807. I overlooked your comment, sorry.

**Comment by AsciiWolf** [comment] 2022-09-13 20:54
It looks like that changing the game language in the "Help" window also causes the game to crash in most cases.

**Comment by cryham** [comment] 2022-09-14 17:09
Duplicate of #83, aka the top critical bug to fix, so I'm closing

**Closed by cryham** 2022-09-14 17:09 UTC
